replicaCount: 2

image:
  repository: acr4llm.azurecr.io/litellm-router
  tag: 0.0.1
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: acr-registry-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

azure:
  secretName: azure-openai

readinessProbe:
  path: /healthz
  initialDelaySeconds: 6
  periodSeconds: 10

livenessProbe:
  path: /healthz
  initialDelaySeconds: 20
  periodSeconds: 20

affinity: {}
nodeSelector: {}
tolerations: []