apiVersion: v1
kind: Secret
metadata:
  name: azure-openai
  namespace: llm-proxy
type: Opaque
stringData:
  AZURE_OPENAI_API_KEY: ""
  AZURE_OPENAI_API_BASE: ""
  AZURE_OPENAI_API_VERSION: "2024-12-01-preview"
  AZURE_OPENAI_DEPLOYMENT: "gpt-4o"