apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azure.secretName }}
type: Opaque
stringData:
  AZURE_OPENAI_API_KEY: {{ .Values.azure.AZURE_OPENAI_API_KEY | default "" }}
  AZURE_OPENAI_API_BASE: {{ .Values.azure.AZURE_OPENAI_API_BASE | default "" }}
  AZURE_OPENAI_API_VERSION: {{ .Values.azure.AZURE_OPENAI_API_VERSION | default "2024-02-01" }}
  AZURE_OPENAI_DEPLOYMENT: {{ .Values.azure.AZURE_OPENAI_DEPLOYMENT | default "" }}